### PR TITLE
Move failing tests to a separate workflow

### PR DESCRIPTION
**Pull request by Nebyt**

### CODE REVIEW

**Review by Nebyt — COMMENTED** [review]
/check

**Review by Nebyt — COMMENTED** [review]
/check

**Review by zuzunker — DISMISSED** [review]

**Review by Nebyt — COMMENTED** [review]
/check

**Review by Nebyt — COMMENTED** [review]
/dapp-general

**Review by Nebyt — COMMENTED** [review]
/check

**Review by Nebyt — COMMENTED** [review]
/ext-general

**Review by zuzunker — COMMENTED** [review]
/check

**Pull request merged**
