### PR TITLE
feat(voting): revamp voting page & dialogs

### PR DESCRIPTION
**Pull request by nistadev**
**Screenshots**

_Main page_
image

_Register dialog_
image

image

### CODE REVIEW

**Comment by neuodev** [comment]
[autoscirpt] Jira Ticket: **[Catalyst Voting](https://emurgo.atlassian.net/browse/YOEXT-679)**

[](__JIRA_COMMENT_FLAG)

**Review by neuodev — COMMENTED** [review]
@nistadev This branch has unrelated changes. Can you please include only the commits related to this PR?

**Comment by neuodev** [comment]
> @nistadev This branch has unrelated changes. Can you please include only the commits related to this PR?

Commit no longer appearing after changing the "base" branch to "develop". 

Conflicts with develop is resolved.

**Review by neuodev — APPROVED** [review]
Great work @nistadev! LGTM!

**Comment by nistadev** [comment]
> > @nistadev This branch has unrelated changes. Can you please include only the commits related to this PR?
> 
> Commit no longer appearing after changing the "base" branch to "develop".
> 
> Conflicts with develop is resolved.

This are the commits related to the branch:
- https://github.com/Emurgo/yoroi-frontend/pull/3273/commits/aa4f02718ddac3e9271b3da971d709c76aa696ae
- https://github.com/Emurgo/yoroi-frontend/pull/3273/commits/542f491cf5bb4183d00ecbbfa6ca2ecb05302208
- https://github.com/Emurgo/yoroi-frontend/pull/3273/commits/ebb904abbc76fa5cd353d7191a62571971c476f8

**Review by zuzunker — APPROVED** [review]

**Pull request merged**
