### PR TITLE
Release/4.22.0

### PR DESCRIPTION
**Pull request by zuzunker**
Milestone: https://github.com/Emurgo/yoroi-frontend/milestone/70?closed=1

## Change Set:
- [x] https://github.com/Emurgo/yoroi-frontend/pull/3171 [@neuodev]
- [x] https://github.com/Emurgo/yoroi-frontend/pull/3200 [@neuodev]
- [x] https://github.com/Emurgo/yoroi-frontend/pull/3204
- [x] https://github.com/Emurgo/yoroi-frontend/pull/3217 [@neuodev]
- [x] https://github.com/Emurgo/yoroi-frontend/pull/3218 [@neuodev]
- [x] https://github.com/Emurgo/yoroi-frontend/pull/3220 [@yushih]
- [x] https://github.com/Emurgo/yoroi-frontend/pull/3226 [@neuodev]
- [x] https://github.com/Emurgo/yoroi-frontend/pull/3227 [@neuodev]
- [x] https://github.com/Emurgo/yoroi-frontend/pull/3238
- [x] https://github.com/Emurgo/yoroi-frontend/pull/3241 [@neuodev]
- [x] https://github.com/Emurgo/yoroi-frontend/pull/3243 [@vsubhuman]
- [x] https://github.com/Emurgo/yoroi-frontend/pull/3245 [@vsubhuman]
- [x] https://github.com/Emurgo/yoroi-frontend/pull/3246 [@vsubhuman]

### CODE REVIEW

**Review by zuzunker — COMMENTED** [review]
/check

**Review by zuzunker — COMMENTED** [review]
/check

**Review by zuzunker — COMMENTED** [review]
/check

**Review by Nebyt — DISMISSED** [review]

**Review by zuzunker — COMMENTED** [review]
/check

**Comment by zuzunker** [comment]
Release: https://github.com/Emurgo/yoroi-frontend/releases/tag/4.22.0

**Pull request merged**
