### PR TITLE
fixing collateral api response in connector

### PR DESCRIPTION
**Pull request by zuzunker**
Changing the connector to not return ever more collateral UTxOs than the maximum allowed of collateral inputs for a TX, which is currently `3`

### CODE REVIEW

**Comment by neuodev** [comment]
[autoscirpt] Jira Ticket: **[[External] Users can't harvest from Sundae](https://emurgo.atlassian.net/browse/YOEXT-819)**

[](__JIRA_COMMENT_FLAG)

**Review by zuzunker — COMMENTED** [review]
/check

**Review by zuzunker — COMMENTED** [review]
/check

**Review by zuzunker — COMMENTED** [review]
/check

**Review by Nebyt — APPROVED** [review]

**Pull request merged**
