### PR TITLE
Added tests for change currency pairing

### PR DESCRIPTION
**Pull request by cmerloglb**

### CODE REVIEW

**Review by zuzunker — COMMENTED** [review]
/check

**Review by cmerloglb — COMMENTED** [review]
/check

**Review by zuzunker — COMMENTED** [review]
/check

**Review by Nebyt — CHANGES_REQUESTED** [review]
Necessary to add to checks for all available fiats.
It necessary to avoid long selectors, such selector a wick point in tests. Please change it https://github.com/Emurgo/yoroi-frontend/pull/2948/files#diff-76b2890a5d6f64c0e0237af42bf8823aa0f1ddd81a2667ef32ac5258a9d91f4fR5

**Review by Nebyt — APPROVED** [review]

**Review by Nebyt — COMMENTED** [review]
/check

**Review by zuzunker — APPROVED** [review]

**Pull request merged**
