### PR TITLE
improved nft check

### PR DESCRIPTION
**Pull request by zuzunker**

### CODE REVIEW

**Comment by neuodev** [comment]
[autoscirpt] Jira Ticket: **[NFT gallery show Tokens that shouldn't be there](https://emurgo.atlassian.net/browse/YOEXT-501)**

[](__JIRA_COMMENT_FLAG)

**Review by zuzunker — COMMENTED** [review]
/check

**Review by Nebyt — DISMISSED** [review]

**Review by yushih — DISMISSED** [review]
LGTM

**Review by zuzunker — COMMENTED** [review]
/check

**Review by zuzunker — COMMENTED** [review]
/check

**Pull request merged**
