### PR TITLE
Release / 4.15.100

### PR DESCRIPTION
**Pull request by zuzunker**
Milestone: https://github.com/Emurgo/yoroi-frontend/milestone/58?closed=1

## Change Set

- [x] https://github.com/Emurgo/yoroi-frontend/pull/2918 [@yushih]
- [x] https://github.com/Emurgo/yoroi-frontend/pull/2919 [@yushih]
- [x] https://github.com/Emurgo/yoroi-frontend/pull/2924 [@yushih]
- [x] https://github.com/Emurgo/yoroi-frontend/pull/2928 [@yushih]
- [x] https://github.com/Emurgo/yoroi-frontend/pull/2929 [@Nebyt]
- [x] https://github.com/Emurgo/yoroi-frontend/pull/2930 [@ozgrakkurt]
- [x] https://github.com/Emurgo/yoroi-frontend/pull/2932 [@Nebyt]

### CODE REVIEW

**Review by Nebyt — DISMISSED** [review]
Checked. Works fine :+1:

**Review by zuzunker — COMMENTED** [review]
/check

**Review by Nebyt — COMMENTED** [review]
/check

**Review by Nebyt — APPROVED** [review]

**Comment by zuzunker** [comment]
Release: https://github.com/Emurgo/yoroi-frontend/releases/tag/4.15.100

**Pull request merged**
