### PR TITLE
QA. Stabilisation of the tests.

### PR DESCRIPTION
**Pull request by Nebyt**

### CODE REVIEW

**Comment by emurgo-rnd** [comment]
[YOEXT-1215: QA. Stabilize tests.](https://emurgo.atlassian.net/browse/YOEXT-1215)

**Review by Nebyt — COMMENTED** [review]
/check

**Review by Nebyt — COMMENTED** [review]
/check

**Review by Nebyt — COMMENTED** [review]
/check

**Review by Nebyt — COMMENTED** [review]
/check

**Review by Nebyt — COMMENTED** [review]
/check

**Review by SorinC6 — APPROVED** [review]

**Pull request merged**
