### PR TITLE
Use Yoroi-lib UtxoService to manage utxo set for Cardano wallets

### PR DESCRIPTION
**Pull request by yushih**
Important reminder: I assume this will be released in version 4.14 so I use this value in the migration code (`adaMigration.js`). Should it not be the case, the value in the code needs to be changed accordingly.

### CODE REVIEW

**Review by zuzunker — COMMENTED** [review]
/check

**Review by zuzunker — APPROVED** [review]

**Review by Nebyt — APPROVED** [review]

**Review by Nebyt — APPROVED** [review]

**Review by zuzunker — COMMENTED** [review]
/check

**Review by Nebyt — COMMENTED** [review]
/check

**Review by zuzunker — APPROVED** [review]

**Review by zuzunker — COMMENTED** [review]
/check

**Review by zuzunker — COMMENTED** [review]
/check

**Review by zuzunker — COMMENTED** [review]
/check

**Comment by zuzunker** [comment]
The change is tested and is getting merged. The tests are getting fixed in a separate branch.

**Pull request merged**
