### PR TITLE
feature: dark theme for swap and staking 

### PR DESCRIPTION
**Pull request by SorinC6**
task: 
- https://emurgo.atlassian.net/browse/YOEXT-1263

### CODE REVIEW

**Comment by emurgo-rnd** [comment]
[YOEXT-1263: Dark theme suport for Swap and Staking features ](https://emurgo.atlassian.net/browse/YOEXT-1263)

**Review by Nebyt — DISMISSED** [review]

**Review by SorinC6 — COMMENTED** [review]
/check

**Review by nistadev — DISMISSED** [review]

**Review by yushih — DISMISSED** [review]
LGTM.

**Review by zuzunker — COMMENTED** [review]
/check

**Pull request merged**
