### PR TITLE
Pat/revamp stacking page

### PR DESCRIPTION
**Pull request by nistadev**
Todo: Remove delegated pool placeholders.

**Before**
image

**After**
image

### CODE REVIEW

**Comment by neuodev** [comment]
@nistadev If this PR is open for review please assign someone else you can convert it to a draft!

**Comment by neuodev** [comment]
Resolve the conflicts plz @nistadev

**Comment by neuodev** [comment]
the extension crashes when navigating to the staking page while the wallet is still checking, plz fix it @nistadev.

**Comment by nistadev** [comment]
I resolved the conflicts and fixed the flow issues. Can you review again @AhmedIbrahim336? Thanks!

**Review by zuzunker — COMMENTED** [review]
/check

**Review by zuzunker — COMMENTED** [review]
/check

**Review by zuzunker — APPROVED** [review]
Thank you, @nistadev !

**Pull request merged**
