### PR TITLE
Added changes to trezor-emulator tests

### PR DESCRIPTION
**Pull request by cmerloglb**

### CODE REVIEW

**Review by cmerloglb — COMMENTED** [review]
/check

**Review by cmerloglb — COMMENTED** [review]
/check

**Review by Nebyt — COMMENTED** [review]
/trezor-check

**Review by Nebyt — APPROVED** [review]

**Review by Nebyt — COMMENTED** [review]
/check

**Review by Nebyt — COMMENTED** [review]
/check

**Review by cmerloglb — COMMENTED** [review]
/check

**Review by zuzunker — APPROVED** [review]

**Pull request merged**
