### PR TITLE
fix(txs): extension crashes after minting an new NFT 

### PR DESCRIPTION
**Pull request by neuodev**

### CODE REVIEW

**Comment by neuodev** [comment]
[autoscirpt] Jira Ticket: **[App crashes after minting NFT](https://emurgo.atlassian.net/browse/YOEXT-565)**

[](__JIRA_COMMENT_FLAG)

**Review by Nebyt — CHANGES_REQUESTED** [review]
The issue is not fixed

**Comment by neuodev** [comment]
> The issue is not fixed

Nice catch! I did other fixes, should be working now!

**Review by Nebyt — APPROVED** [review]
Checked. Fixed.

**Review by zuzunker — APPROVED** [review]

**Pull request merged**
