### PR TITLE
fix: Delegate modal dialog

### PR DESCRIPTION
**Pull request by SorinC6**
issue: 
- https://emurgo.atlassian.net/browse/YOEXT-1225
- https://emurgo.atlassian.net/browse/YOEXT-1138
- https://emurgo.atlassian.net/browse/YOEXT-1208

### CODE REVIEW

**Comment by emurgo-rnd** [comment]
[YOEXT-1225: Staking. Delegate modal window appears every time user opens the Staking page.](https://emurgo.atlassian.net/browse/YOEXT-1225)

**Review by Nebyt — DISMISSED** [review]
Fixed. 🚀

**Review by Nebyt — DISMISSED** [review]

**Review by SorinC6 — COMMENTED** [review]
/check

**Review by Nebyt — DISMISSED** [review]

**Review by zuzunker — DISMISSED** [review]

**Review by zuzunker — APPROVED** [review]

**Pull request merged**
