### PR TITLE
Removing Legacy Claim/Transfer functionality

### PR DESCRIPTION
**Pull request by zuzunker**
1. Claim/Transfer entirely removed from revamp
2. In legacy layout all claim/transfer functionality is removed except "Legacy Yoroi paper wallets"
3. Steps are removed so that it's a single click from the page into the paper-wallet claiming popup

A bunch of no longer used code is removed.

<details><summary>Claim / Transfer Page Preview</summary>
<p>

Screenshot 2023-09-14 at 12 55 31 PM

</p>
</details>

### CODE REVIEW

**Comment by neuodev** [comment]
[autoscirpt] Jira Ticket: **[Remove entire claim/transfer section from the revamp and most of it from the legacy as well](https://emurgo.atlassian.net/browse/YOEXT-713)**

[](__JIRA_COMMENT_FLAG)

**Review by neuodev — COMMENTED** [review]
Nice! works as expected! 

The only issue I found was that the "transfer" page is accessible in the revamp **through the link** 

Screenshot 2023-09-14 at 12 57 39 PM

it would be nice if we could redirect the user to the wallets page "/wallets"

**Comment by zuzunker** [comment]
> The only issue I found was that the "transfer" page is accessible in the revamp **through the link**

Heck! Nice catch! Thank you, @neuodev. Fixing it

**Review by zuzunker — COMMENTED** [review]
/check

**Pull request merged**
