### PR TITLE
use consistently cardano-serialization-lib version 12

### PR DESCRIPTION
**Pull request by yushih**

### CODE REVIEW

**Comment by neuodev** [comment]
[autoscirpt] Jira Ticket: **[The app crashes while trying to make a transaction](https://emurgo.atlassian.net/browse/YOEXT-783)**

[](__JIRA_COMMENT_FLAG)

**Review by zuzunker — APPROVED** [review]
Thank you, @yushih !

**Review by zuzunker — COMMENTED** [review]
/check

**Review by zuzunker — COMMENTED** [review]
/check

**Review by zuzunker — COMMENTED** [review]
/check

**Review by zuzunker — COMMENTED** [review]
/check

**Review by zuzunker — COMMENTED** [review]
/check

**Review by zuzunker — COMMENTED** [review]
/check

**Review by zuzunker — COMMENTED** [review]
/check

**Review by zuzunker — COMMENTED** [review]
/check

**Review by zuzunker — COMMENTED** [review]
/check

**Pull request merged**
