### PR TITLE
E2E-tests. Deleting memo.

### PR DESCRIPTION
**Pull request by Nebyt**

### CODE REVIEW

**Comment by emurgo-rnd** [comment]
[YOEXT-1172: E2E-tests. Deleting memo.](https://emurgo.atlassian.net/browse/YOEXT-1172)

**Review by Nebyt — COMMENTED** [review]
/check

**Review by Nebyt — COMMENTED** [review]
/check

**Review by Nebyt — COMMENTED** [review]
/check

**Review by SorinC6 — APPROVED** [review]

**Pull request merged**
