### PR TITLE
time util untangle

### PR DESCRIPTION
**Pull request by zuzunker**
https://emurgo.atlassian.net/browse/YOEXT-1174

### CODE REVIEW

**Review by zuzunker — COMMENTED** [review]
/check

**Review by yushih — DISMISSED** [review]

**Review by zuzunker — COMMENTED** [review]
/check

**Comment by zuzunker** [comment]
[YOEXT-1174: Untangle time-util functions](https://emurgo.atlassian.net/browse/YOEXT-1174)

**Review by zuzunker — COMMENTED** [review]
/check

**Pull request merged**
