### PR TITLE
E2E tests. Handle handles.

### PR DESCRIPTION
**Pull request by Nebyt**

### CODE REVIEW

**Comment by emurgo-rnd** [comment]
[YOEXT-1227: E2E tests. Handle handles.](https://emurgo.atlassian.net/browse/YOEXT-1227)

**Review by Nebyt — COMMENTED** [review]
/check

**Review by Nebyt — COMMENTED** [review]
/check

**Review by Nebyt — COMMENTED** [review]
/check

**Review by Nebyt — COMMENTED** [review]
/check

**Review by Nebyt — COMMENTED** [review]
/check

**Review by SorinC6 — DISMISSED** [review]

**Review by zuzunker — APPROVED** [review]

**Pull request merged**
