### PR TITLE
ergo-lib updated to 0.13.2

### LINKED ISSUE #2168: Update ergo-lib-wasm to 0.13.2
There was a bug in ErgoTree serialization which was fixed in `0.13.2`

### PR DESCRIPTION
**Pull request by oskin1**
Close #2168

### CODE REVIEW

**Comment by rooooooooob** [comment]
Are there any API changes in sigma-rust at all going from 0.13.1 to 0.13.2, or just fixes? We use flow to do type checking but these flow definitions needs to be manually generated from the .ts file in the wasm build for sigma-rust (with some manual fix-ups since that doesn't handle enums correctly if you do it via flowgen + we add additional info for the JSON functions). However, if there are no API changes this looks fine. I'm assuming nothing changed since it is a minor version update.

**Comment by oskin1** [comment]
> Are there any API changes in sigma-rust at all going from 0.13.1 to 0.13.2, or just fixes? We use flow to do type checking but these flow definitions needs to be manually generated from the .ts file in the wasm build for sigma-rust (with some manual fix-ups since that doesn't handle enums correctly if you do it via flowgen + we add additional info for the JSON functions). However, if there are no API changes this looks fine. I'm assuming nothing changed since it is a minor version update.

No changes in existing API, just improvements. 

https://github.com/ergoplatform/sigma-rust/releases/tag/ergo-lib-v0.13.2

**Review by rooooooooob — APPROVED** [review]
LGTM

**Comment by rooooooooob** [comment]
@oskin1 You'll need to resolve the package-lock conflict though as we just merged a PR I think the day before that touched it (updating the dev version of sigma-rust from 0.10.0 to 0.13.1). Once you do that I can merge this.

**Comment by oskin1** [comment]
> @oskin1 You'll need to resolve the package-lock conflict though as we just merged a PR I think the day before that touched it (updating the dev version of sigma-rust from 0.10.0 to 0.13.1). Once you do that I can merge this.

Done. Updated `ergo-lib` to `0.13.3` along the way (https://github.com/ergoplatform/sigma-rust/releases/tag/ergo-lib-v0.13.3).

**Review by zuzunker — COMMENTED** [review]
/check

**Review by zuzunker — APPROVED** [review]

**Review by zuzunker — COMMENTED** [review]
/check

**Pull request merged**
