### PR TITLE
sancho

### PR DESCRIPTION
**Pull request by zuzunker**

### CODE REVIEW

**Comment by neuodev** [comment]
[autoscirpt] Jira Ticket: **[Add Sanchonet support](https://emurgo.atlassian.net/browse/YOEXT-866)**

[](__JIRA_COMMENT_FLAG)

**Review by zuzunker — COMMENTED** [review]
/check

**Review by zuzunker — COMMENTED** [review]
/check

**Review by zuzunker — COMMENTED** [review]
/check

**Pull request merged**
