### PR TITLE
Release / 4.11.100

### PR DESCRIPTION
**Pull request by zuzunker**
Milestone: https://github.com/Emurgo/yoroi-frontend/milestone/40?closed=1

## Change Set
- [x] https://github.com/Emurgo/yoroi-frontend/pull/2736 [@AhmedIbrahim336]
- [x] https://github.com/Emurgo/yoroi-frontend/pull/2739 [@AhmedIbrahim336]
- [x] https://github.com/Emurgo/yoroi-frontend/pull/2741 [@yushih]
- [x] https://github.com/Emurgo/yoroi-frontend/pull/2742 [@vsubhuman]
- [x] https://github.com/Emurgo/yoroi-frontend/pull/2745 [@vsubhuman]

### CODE REVIEW

**Comment by Nebyt** [comment]
@vsubhuman GTG

**Review by zuzunker — COMMENTED** [review]
/check

**Review by zuzunker — COMMENTED** [review]
/check

**Comment by zuzunker** [comment]
Release: https://github.com/Emurgo/yoroi-frontend/releases/tag/4.11.100

**Pull request merged**
