### PR TITLE
Tests/yoext 752/dapp tests fix

### PR DESCRIPTION
**Pull request by Nebyt**

### CODE REVIEW

**Comment by neuodev** [comment]
[autoscirpt] Jira Ticket: **[Fix dApp tests](https://emurgo.atlassian.net/browse/YOEXT-752)**

[](__JIRA_COMMENT_FLAG)

**Review by Nebyt — COMMENTED** [review]
/dapp-check

**Review by zuzunker — COMMENTED** [review]
/check

**Review by zuzunker — APPROVED** [review]
sweet

**Pull request merged**
