### PR TITLE
E2E tests. Sending to incorrect address.

### PR DESCRIPTION
**Pull request by Nebyt**

### CODE REVIEW

**Comment by emurgo-rnd** [comment]
[YOEXT-1228: E2E tests. Sending to incorrect address.](https://emurgo.atlassian.net/browse/YOEXT-1228)

**Review by Nebyt — COMMENTED** [review]
/check

**Review by Nebyt — COMMENTED** [review]
/check

**Review by Nebyt — COMMENTED** [review]
/check

**Review by SorinC6 — DISMISSED** [review]

**Review by zuzunker — APPROVED** [review]

**Pull request merged**
