### PR TITLE
fix: overall app background on light/dark theme 

### PR DESCRIPTION
**Pull request by SorinC6**
task: 
- https://emurgo.atlassian.net/browse/YOEXT-1332
- https://emurgo.atlassian.net/browse/YOEXT-1328

### CODE REVIEW

**Comment by emurgo-rnd** [comment]
[YOEXT-1332: [Dark theme] The app crashes on creating a new wallet](https://emurgo.atlassian.net/browse/YOEXT-1332)

**Comment by emurgo-rnd** [comment]
[YOEXT-1328: [Wallet][Dark theme] Background color is different from the design](https://emurgo.atlassian.net/browse/YOEXT-1328)

**Review by SorinC6 — COMMENTED** [review]
/check

**Review by SorinC6 — COMMENTED** [review]
/check

**Review by Nebyt — APPROVED** [review]

**Pull request merged**
