### PR TITLE
updates - dark theme swap + governance

### PR DESCRIPTION
**Pull request by SorinC6**
tasks:

- https://emurgo.atlassian.net/browse/YOEXT-1383
- https://emurgo.atlassian.net/browse/YOEXT-1358
- https://emurgo.atlassian.net/browse/YOEXT-1357
- https://emurgo.atlassian.net/browse/YOEXT-1356
- https://emurgo.atlassian.net/browse/YOEXT-1355
- https://emurgo.atlassian.net/browse/YOEXT-1354
- https://emurgo.atlassian.net/browse/YOEXT-1353
- https://emurgo.atlassian.net/browse/YOEXT-1352
- https://emurgo.atlassian.net/browse/YOEXT-1351
- https://emurgo.atlassian.net/browse/YOEXT-1350

### CODE REVIEW

**Review by SorinC6 — COMMENTED** [review]
/check

**Review by Nebyt — DISMISSED** [review]

**Review by SorinC6 — COMMENTED** [review]
/check

**Review by SorinC6 — COMMENTED** [review]
/check

**Review by zuzunker — COMMENTED** [review]
/check

**Pull request merged**
