### PR TITLE
Add staking page revamp

### PR DESCRIPTION
**Pull request by paulclindo**
[UPDATE] 

Demo:
Screen Recording 2021-11-10 at 03 06 46 AM
 

- Staking page
Screen Shot 2021-10-26 at 11 04 53 PM

### CODE REVIEW

**Comment by Marta-Ryzhok** [comment]
Thanks for sharing! 

Some fixes
1. Add icons and tooltips next to the "Roa" and "First Reward" 
image

tooltips are in the design
https://projects.invisionapp.com/d/main#/console/21482837/455990156/preview
https://projects.invisionapp.com/d/main#/console/21482837/455991190/preview

**Comment by Marta-Ryzhok** [comment]
2. Make the button "Delegate" disable until user fill the wallet with some ADA
image

Design reference
https://projects.invisionapp.com/d/main#/console/21482837/455991190/preview
disable button https://projects.invisionapp.com/d/main#/console/21682093/458875679/preview

**Comment by Marta-Ryzhok** [comment]
3. Please double-check the font style in buttons, it looks regular but should be medium (a bit bolder)

image

image


-

**Comment by Marta-Ryzhok** [comment]
4. Fix title of the page to Staking Dashboard, only on the side bar navigation we keep one word "staking" for the sake of space

image

**Comment by Marta-Ryzhok** [comment]
5. in top wallet navigaion, please move vallue closer to the eye icon, because these elements are related when notification is independent element. 
Why there is ADA and USD together? I guess it's just a placeholder for a now?
Also, there is a grey circle behind the notification icon, I believe that's the view on hover only not default state, yes?

image

**Review by zuzunker — APPROVED** [review]

**Pull request merged**
