### PR TITLE
Nightly / 4.5.5001

### PR DESCRIPTION
**Pull request by zuzunker**
## Last prod: `4.5.5`

https://github.com/Emurgo/yoroi-frontend/releases/tag/4.5.5

## Main includes after last prod

1. Hardware wallets support for Catalyst
2. Ergo p2s and data-inputs, plus latest fixes, plus migration to sigma-rust 13.3

## Full PR diff since last prod

- https://github.com/Emurgo/yoroi-frontend/pull/2081 - 'Data inputs + P2S support' [@rooooooooob]
- https://github.com/Emurgo/yoroi-frontend/pull/2087 - 'buid(yoroi-extension): buld scripts now compatible with Windows' [@danielmain]
- https://github.com/Emurgo/yoroi-frontend/pull/2096 - 'Ledger wallet Catalyst voting registration support' [@yushih]
- https://github.com/Emurgo/yoroi-frontend/pull/2100 - 'UI updates for hardware wallet Catalyst registration' [@yushih]
- https://github.com/Emurgo/yoroi-frontend/pull/2103 - 'Migration to SigmaRust 0.13.x' [@oskin1]
- https://github.com/Emurgo/yoroi-frontend/pull/2114 - 'Fix Catalyst round Info in UI' [@v-almonacid]
- https://github.com/Emurgo/yoroi-frontend/pull/2119 - 'Add github actions to do flow and lint checks' [@yushih]
- https://github.com/Emurgo/yoroi-frontend/pull/2120 - 'Sigma Rust some Flow fixes' [@vantuz-subhuman]
- https://github.com/Emurgo/yoroi-frontend/pull/2122 - 'Ergo Flow and Lint fixes' [@vantuz-subhuman]
- https://github.com/Emurgo/yoroi-frontend/pull/2151 - 'Fix for Ergo unknown address type error in develop' [@rooooooooob]
- https://github.com/Emurgo/yoroi-frontend/pull/2166 - 'Fixes for issues caused when sigma-rust was updated to 0.13.1' [@rooooooooob]
- https://github.com/Emurgo/yoroi-frontend/pull/2169 - 'ergo-lib updated to 0.13.2' [@oskin1]
- https://github.com/Emurgo/yoroi-frontend/pull/2170 - 'Ergo Connector: Fix crash when signing a TX that mints new assets' [@rooooooooob]
- https://github.com/Emurgo/yoroi-frontend/pull/2171 - 'change icon "transactions" ' [@AhmedIbrahim336]
- https://github.com/Emurgo/yoroi-frontend/pull/2172 - 'Update the eye icon in the input field and update the logic' [@AhmedIbrahim336]
- https://github.com/Emurgo/yoroi-frontend/pull/2173 - 'Enable tests in gh checks' [@vantuz-subhuman]
- https://github.com/Emurgo/yoroi-frontend/pull/2178 - 'Tab icons css tiny fix' [@vantuz-subhuman]

### CODE REVIEW

**Review by zuzunker — COMMENTED** [review]
/check

**Review by zuzunker — COMMENTED** [review]
/check

**Comment by zuzunker** [comment]
Tag: https://github.com/Emurgo/yoroi-frontend/releases/tag/nightly%2F4.5.5001

**Review by rooooooooob — COMMENTED** [review]
LGTM from the commits on my end at least. Those fixes resolving the issues are in here too so there should be no issue with the P2S/0.13.* sigma-rust updates.

**Pull request merged**
