### PR TITLE
Denis/new ci workflow

### PR DESCRIPTION
**Pull request by Nebyt**
The new workflow for regression tests

### CODE REVIEW

**Review by Nebyt — COMMENTED** [review]
/regression-check

**Review by Nebyt — COMMENTED** [review]
/regression-check

**Review by Nebyt — COMMENTED** [review]
/regression-check

**Review by Nebyt — COMMENTED** [review]
/trezor-check

**Review by Nebyt — COMMENTED** [review]
/regression-check

**Review by zuzunker — APPROVED** [review]

**Pull request merged**
