### PR TITLE
Release / 5.0.100

### PR DESCRIPTION
**Pull request by zuzunker**
Milestone: https://github.com/Emurgo/yoroi-frontend/milestone/86?closed=1

## Change Set
- [ ] https://github.com/Emurgo/yoroi-frontend/pull/3367 [@nistadev]
- [ ] https://github.com/Emurgo/yoroi-frontend/pull/3368 [@nistadev]
- [ ] https://github.com/Emurgo/yoroi-frontend/pull/3370 [@vsubhuman]

### CODE REVIEW

**Comment by neuodev** [comment]
[autoscript] ⚠️ `release/5.0.100` doesn't full our branch naming convention.
Should follow `<tag>/<jira-ticket-id>/<short-name>`
<details>
<summary>Details</summary>

- `<tag>`: `fix`, `feat`, `chore`, `refactor`, `test`, ...
- `<jira-ticket-id>`: The issue ID of JIRA all capital letters
- `<short-name>`: A short and descriptive name for the branch
</details>

[](__JIRA_COMMENT_FLAG)

**Review by zuzunker — COMMENTED** [review]
/check

**Review by zuzunker — COMMENTED** [review]
/check

**Comment by zuzunker** [comment]
Release: https://github.com/Emurgo/yoroi-frontend/releases/tag/5.0.100

**Pull request merged**
