### PR TITLE
moved some types into other related modules to remove few files

### PR DESCRIPTION
**Pull request by zuzunker**

### CODE REVIEW

**Comment by neuodev** [comment]
[autoscript] ⚠️ `ruslan/moving-some-types` doesn't full our branch naming convention.
Should follow `<tag>/<jira-ticket-id>/<short-name>`
<details>
<summary>Details</summary>

- `<tag>`: `fix`, `feat`, `chore`, `refactor`, `test`, ...
- `<jira-ticket-id>`: The issue ID of JIRA all capital letters
- `<short-name>`: A short and descriptive name for the branch
</details>

[](__JIRA_COMMENT_FLAG)

**Review by yushih — DISMISSED** [review]
Too many changed to review line by line, but what I sampled looks good and since the changes are mostly renames, I guess as long as the tool chains are happy there would be no problem.

**Comment by Nebyt** [comment]
LGTM

**Review by zuzunker — COMMENTED** [review]
/check

**Pull request merged**
