### PR TITLE
Sorin/yoext 1213/swap UI fixes

### PR DESCRIPTION
**Pull request by SorinC6**
tasks:
- https://emurgo.atlassian.net/browse/YOEXT-1213
- https://emurgo.atlassian.net/browse/YOEXT-1212
- https://emurgo.atlassian.net/browse/YOEXT-1211
- https://emurgo.atlassian.net/browse/YOEXT-1210
- https://emurgo.atlassian.net/browse/YOEXT-1207
- https://emurgo.atlassian.net/browse/YOEXT-1206

### CODE REVIEW

**Comment by emurgo-rnd** [comment]
[YOEXT-1213: [UAT] Incorrect horizontal alignment for the price impact triangular exclamation icon](https://emurgo.atlassian.net/browse/YOEXT-1213)

**Comment by emurgo-rnd** [comment]
[YOEXT-1210: [UAT] Incorrect transaction success screen alignment ](https://emurgo.atlassian.net/browse/YOEXT-1210)

**Comment by emurgo-rnd** [comment]
[YOEXT-1207: [UAT] Incorrect horizontal alignment for the info icon](https://emurgo.atlassian.net/browse/YOEXT-1207)

**Comment by emurgo-rnd** [comment]
[YOEXT-1212: [UAT] Incorrect corner radius in the asset image](https://emurgo.atlassian.net/browse/YOEXT-1212)

**Comment by emurgo-rnd** [comment]
[YOEXT-1206: [UAT] Incorrect spacing in different Swap places](https://emurgo.atlassian.net/browse/YOEXT-1206)

**Review by nistadev — DISMISSED** [review]

**Review by Nebyt — DISMISSED** [review]

**Review by zuzunker — APPROVED** [review]

**Review by zuzunker — COMMENTED** [review]
/check

**Pull request merged**
