### PR TITLE
[5.3.120] pool update fix

### PR DESCRIPTION
**Pull request by zuzunker**
1. pool update fix
2. network config update
3. flag check for governance removed
4. csl update

### CODE REVIEW

**Comment by emurgo-rnd** [comment]
[YOEXT-1372: [Stake Pool Migration] Not able to update an old pool](https://emurgo.atlassian.net/browse/YOEXT-1372)

**Review by Nebyt — DISMISSED** [review]
Checked.

**Review by zuzunker — COMMENTED** [review]
/check

**Review by zuzunker — COMMENTED** [review]
/check

**Pull request merged**
