### PR TITLE
bump node version to 18.18.2

### PR DESCRIPTION
**Pull request by yushih**
Have to use `npm i --legacy-peer-deps` to install deps now.

### CODE REVIEW

**Comment by neuodev** [comment]
[autoscirpt] Jira Ticket: **[Upgrade to node 18](https://emurgo.atlassian.net/browse/YOEXT-868)**

[](__JIRA_COMMENT_FLAG)

**Review by zuzunker — COMMENTED** [review]
/check

**Review by zuzunker — COMMENTED** [review]
/check

**Review by zuzunker — COMMENTED** [review]
/check

**Review by zuzunker — APPROVED** [review]

**Pull request merged**
