### PR TITLE
refactor: change token names 

### PR DESCRIPTION
**Pull request by SorinC6**
⚠️ Huge PR alert

- as the design team decided to change the token names we are forced to have this huge PR in which we are changing: child and primary token names to reflect the design all over the application
- I've been delaying this but now we need to update it as there are noticeable differences when building the UI in Figma with what we have related to the token's name

### CODE REVIEW

**Comment by emurgo-rnd** [comment]
[YOEXT-1271: Dark theme support for Wallet, Voting and Connector features](https://emurgo.atlassian.net/browse/YOEXT-1271)

**Review by SorinC6 — COMMENTED** [review]
/check

**Review by zuzunker — DISMISSED** [review]
Thank you, @SorinC6 !

**Review by SorinC6 — COMMENTED** [review]
/check

**Pull request merged**
