### PR TITLE
Denis/trezor ci

### PR DESCRIPTION
**Pull request by Nebyt**
Added the CI for testing with the trezor emulator

### CODE REVIEW

**Review by Nebyt — COMMENTED** [review]
/trezor-chrome

**Review by Nebyt — COMMENTED** [review]
/trezor-chrome

**Review by Nebyt — COMMENTED** [review]
/trezor-chrome

**Review by Nebyt — COMMENTED** [review]
/trezor-chrome

**Review by Nebyt — COMMENTED** [review]
/trezor-chrome

**Review by Nebyt — COMMENTED** [review]
/trezor-chrome

**Review by Nebyt — COMMENTED** [review]
/trezor-chrome

**Review by Nebyt — COMMENTED** [review]
/trezor-chrome

**Review by Nebyt — COMMENTED** [review]
/trezor-chrome

**Review by Nebyt — COMMENTED** [review]
/trezor-firefox

**Review by Nebyt — COMMENTED** [review]
/trezor-firefox

**Review by Nebyt — COMMENTED** [review]
/trezor-firefox

**Review by Nebyt — COMMENTED** [review]
/trezor-firefox

**Review by Nebyt — COMMENTED** [review]
/trezor-firefox

**Review by Nebyt — COMMENTED** [review]
/trezor-firefox

**Review by Nebyt — COMMENTED** [review]
/check

**Review by cmerloglb — APPROVED** [review]

**Pull request closed without merging**
