### PR TITLE
Added basic UML diagrams

### PR DESCRIPTION
**Pull request by crchemist-ip**
Added modelio project with next diagrams: component diagram, sequence diagram for basic use cases(create new wallet, send funds).

### CODE REVIEW

**Comment by nicarq** [comment]
LGTM! I had issues with Modelio in MacOSX :/ @sarveshwar-singh or @SebastienGllmt could you try to load the models in modelio whenever you can?

**Comment by sarveshwar-singh** [comment]
@crchemist-ip 
Thanks for your effort, appreciate this !!

I was trying to install and got this:
image


could you please add documentation how to install and use this ULM project?
you may consider:
1. Windows (Yoroi does not build yet on Windows but very soon it will be)
2. Linux
3. Mac

**Comment by crchemist-ip** [comment]
@sarveshwar-singh updated README

**Comment by vantuz-subhuman** [comment]
image

@crchemist-ip, is this like two different databases, or two APIs for the same DB? A bit confused about this part.

**Pull request merged**
