### PR TITLE
feat(wallet): remove Jormungandr the codebase 

### PR DESCRIPTION
**Pull request by neuodev**

### CODE REVIEW

**Review by zuzunker — COMMENTED** [review]
/check

**Comment by neuodev** [comment]
There is about 32 flow errors, need to fix them first

**Review by zuzunker — APPROVED** [review]
🎉

**Comment by neuodev** [comment]
[autoscirpt] Jira Ticket: **[Jormungdone](https://emurgo.atlassian.net/browse/YOEXT-618)**

[](__JIRA_COMMENT_FLAG)

**Review by neuodev — COMMENTED** [review]
/test

**Review by zuzunker — COMMENTED** [review]
/check

**Pull request merged**
