### PR TITLE
Make test runs robust and reliable

### PR DESCRIPTION
**Pull request by Nebyt**

### CODE REVIEW

**Comment by emurgo-rnd** [comment]
[YOEXT-1200: Make test runs robust and reliable](https://emurgo.atlassian.net/browse/YOEXT-1200)

**Review by Nebyt — COMMENTED** [review]
/check

**Review by Nebyt — COMMENTED** [review]
/check

**Review by Nebyt — COMMENTED** [review]
/check

**Review by Nebyt — COMMENTED** [review]
/check

**Review by Nebyt — COMMENTED** [review]
/check

**Review by Nebyt — COMMENTED** [review]
/ext-general

**Review by Nebyt — COMMENTED** [review]
/ext-general

**Review by Nebyt — COMMENTED** [review]
/ext-general

**Review by Nebyt — COMMENTED** [review]
/check

**Review by Nebyt — COMMENTED** [review]
/ext-general

**Review by Nebyt — COMMENTED** [review]
/dapp-general

**Review by Nebyt — COMMENTED** [review]
/ext-general

**Review by Nebyt — COMMENTED** [review]
/ext-general

**Review by Nebyt — COMMENTED** [review]
/ext-general

**Review by Nebyt — COMMENTED** [review]
/ext-general

**Review by Nebyt — COMMENTED** [review]
/ext-general

**Review by Nebyt — COMMENTED** [review]
/ext-general

**Review by Nebyt — COMMENTED** [review]
/ext-general

**Review by Nebyt — COMMENTED** [review]
/ext-general

**Review by Nebyt — COMMENTED** [review]
/ext-general

**Review by Nebyt — COMMENTED** [review]
/ext-general

**Review by Nebyt — COMMENTED** [review]
/ext-general

**Review by Nebyt — COMMENTED** [review]
/ext-general

**Review by Nebyt — COMMENTED** [review]
/check

**Review by Nebyt — COMMENTED** [review]
/check

**Review by Nebyt — COMMENTED** [review]
/check

**Review by Nebyt — COMMENTED** [review]
/ext-general

**Review by Nebyt — COMMENTED** [review]
/ext-general

**Review by Nebyt — COMMENTED** [review]
/ext-general

**Review by Nebyt — COMMENTED** [review]
/ext-general

**Review by Nebyt — COMMENTED** [review]
/ext-general

**Review by Nebyt — COMMENTED** [review]
/ext-general

**Review by Nebyt — COMMENTED** [review]
/ext-general

**Review by Nebyt — COMMENTED** [review]
/ext-general

**Review by Nebyt — COMMENTED** [review]
/ext-general

**Review by Nebyt — COMMENTED** [review]
/check

**Review by Nebyt — COMMENTED** [review]
/check

**Review by Nebyt — COMMENTED** [review]
/check

**Pull request closed without merging**
