### PR TITLE
ledger wallet connector supports Babbage output format

### PR DESCRIPTION
**Pull request by yushih**

### CODE REVIEW

**Comment by neuodev** [comment]
[autoscirpt] Jira Ticket: **[The transaction hash computed by Yoroi extension and that by the device mismatch.](https://emurgo.atlassian.net/browse/YOEXT-563)**

[](__JIRA_COMMENT_FLAG)

**Comment by yushih** [comment]
Rebased onto [release/4.19.200](https://github.com/Emurgo/yoroi-frontend/tree/release/4.19.200)

**Review by Nebyt — APPROVED** [review]
Checked with several dApps. Fixed. :rocket:

**Review by zuzunker — APPROVED** [review]
Thank you, @yushih !

**Review by Nebyt — COMMENTED** [review]
/check

**Pull request merged**
