### PR TITLE
fixes (swap) UI fixes

### PR DESCRIPTION
**Pull request by SorinC6**
- https://emurgo.atlassian.net/browse/YOEXT-1104
- https://emurgo.atlassian.net/browse/YOEXT-1105
- https://emurgo.atlassian.net/browse/YOEXT-1110
- https://emurgo.atlassian.net/browse/YOEXT-1123
- https://emurgo.atlassian.net/browse/YOEXT-1128
- https://emurgo.atlassian.net/browse/YOEXT-1129
- https://emurgo.atlassian.net/browse/YOEXT-1134

### CODE REVIEW

**Comment by zuzunker** [comment]
[YOEXT-1104: [UI] Selected tab has a different color](https://emurgo.atlassian.net/browse/YOEXT-1104)

**Comment by zuzunker** [comment]
[YOEXT-1129: [UI] The height and spacing for the search input is different from the design](https://emurgo.atlassian.net/browse/YOEXT-1129)

**Comment by zuzunker** [comment]
[YOEXT-1105: [UI] Wrong color of not selected tab](https://emurgo.atlassian.net/browse/YOEXT-1105)

**Comment by zuzunker** [comment]
[YOEXT-1123: [UI] The slippage tolerance modal window content should have equal paddings](https://emurgo.atlassian.net/browse/YOEXT-1123)

**Comment by zuzunker** [comment]
[YOEXT-1110: [UI] Info titles have a different color from the design](https://emurgo.atlassian.net/browse/YOEXT-1110)

**Review by Nebyt — APPROVED** [review]

**Pull request merged**
