### PR TITLE
Fix null checks (sketchy lints)

### PR DESCRIPTION
**Pull request by leivaburto**
Unfortunately, some of the changes suggested by flow's sketchy lints for null checks (PR #949) do not reflect the same behavior they did before, so for example in some cases is also necessary to check for empty strings.

At least two UI issues have popped up because of this, so it's necessary to double check the rest of the null checks introduced in #949 (WIP).

Issue 1: https://app.clubhouse.io/emurgo/story/2003/fix-spacing-in-restore-wallet-dialog
Issue 2: https://app.clubhouse.io/emurgo/story/2000/fix-amount-input-spacing-in-the-send-screen

### CODE REVIEW

**Comment by leivaburto** [comment]
cc @SebastienGllmt

**Comment by SebastienGllmt** [comment]
I approve whatever changes need to be made. Unfortunately the screenshot tests are supposed to help avoid problems like this but CI has been so unstable these past few months (seems like every time we fix a stability issue a new one comes up) so screenshot tests rarely ever trigger anymore.

Storybook is meant to help fix the problem with screenshot tests but we just haven't had time to create stories for all our UIs

**Comment by nicarq** [comment]
@sarveshwar-singh did you reviewed this?

**Comment by sarveshwar-singh** [comment]
`fee` text bottom margin have been decreased.
 
image

**Comment by sarveshwar-singh** [comment]
@nicarq DONE.

**Pull request merged**
