### PR TITLE
Collateral coin-selection

### PR DESCRIPTION
**Pull request by zuzunker**

### CODE REVIEW

**Comment by neuodev** [comment]
I am unable to submit a transaction from this branch. I am getting this error `txBuilder.get_total_output is not a function`
Note: it working on `develop`. I am using `abandon` wallet

**Review by zuzunker — COMMENTED** [review]
/check

**Review by zuzunker — COMMENTED** [review]
/check

**Review by zuzunker — COMMENTED** [review]
/check

**Review by zuzunker — COMMENTED** [review]
/check

**Review by zuzunker — COMMENTED** [review]
/check

**Pull request merged**
