### PR TITLE
[Memory Leak] Migrate to WasmScope Pt.3

### PR DESCRIPTION
**Pull request by neuodev**

### CODE REVIEW

**Comment by neuodev** [comment]
⚠️  This one should be reviewed after #3111 . After #3111  got merged we should update the target branch of the PR to be `develop`

**Comment by AhmedIbrahim336** [comment]
Updated

**Comment by AhmedIbrahim336** [comment]
[auto] ⚠️ `Ahmed/wasm-scope-2` doesn't full our branch naming convention.
Should follow `<tag>/<jira-ticket-id>/<short-name>`

**Comment by AhmedIbrahim336** [comment]
[auto-script] ⚠️ `Ahmed/wasm-scope-2` doesn't full our branch naming convention.
Should follow `<tag>/<jira-ticket-id>/<short-name>`
<details>
<summary>Details</summary>
- `fix`: `fix`, `feat`, `chore`, `refactor`, `test`
- `<jira-ticket-id>`: The issue ID of JIRA all capital letters
- `<short-name>`: A short and descriptive name for the branch
</details>

**Comment by AhmedIbrahim336** [comment]
[auto-script] ⚠️ `Ahmed/wasm-scope-2` doesn't full our branch naming convention.
Should follow `<tag>/<jira-ticket-id>/<short-name>`
<details>
<summary>Details</summary>

- `fix`: `fix`, `feat`, `chore`, `refactor`, `test`
- `<jira-ticket-id>`: The issue ID of JIRA all capital letters
- `<short-name>`: A short and descriptive name for the branch
</details>

**Comment by AhmedIbrahim336** [comment]
[autoscirpt] Jira Ticket: **[[dApp-Connector] Difference in window's behavior on Chrome and Firefox](https://emurgo.atlassian.net/browse/YOEXT-10)**

**Comment by AhmedIbrahim336** [comment]
[autoscirpt] Jira Ticket: **[[dApp-Connector] Difference in window's behavior on Chrome and Firefox](https://emurgo.atlassian.net/browse/YOEXT-10)**

**Comment by AhmedIbrahim336** [comment]
[autoscirpt] Jira Ticket: **[[dApp-Connector] Difference in window's behavior on Chrome and Firefox](https://emurgo.atlassian.net/browse/YOEXT-10)**

**Comment by AhmedIbrahim336** [comment]
[autoscirpt] Jira Ticket: **[[dApp-Connector] Difference in window's behavior on Chrome and Firefox](https://emurgo.atlassian.net/browse/YOEXT-10)** [](__JIRA_COMMENT_FLAG)

**Comment by neuodev** [comment]
[autoscript] ⚠️ `Ahmed/wasm-scope-2` doesn't full our branch naming convention.
Should follow `<tag>/<jira-ticket-id>/<short-name>`
<details>
<summary>Details</summary>

- `<tag>`: `fix`, `feat`, `chore`, `refactor`, `test`, ...
- `<jira-ticket-id>`: The issue ID of JIRA all capital letters
- `<short-name>`: A short and descriptive name for the branch
</details>

[](__JIRA_COMMENT_FLAG)

**Review by zuzunker — APPROVED** [review]
Thank you, @AhmedIbrahim336 !

**Review by zuzunker — COMMENTED** [review]
/check

**Pull request merged**
