### PR TITLE
Lock screen functionality

### PR DESCRIPTION
**Pull request by JizKadasha**
@nicarq please check it carefully before merging, need to know if I have to change something

### CODE REVIEW

**Comment by sarveshwar-singh** [comment]
test

**Comment by nicarq** [comment]
@sarveshwar-singh great feedback!!

**Comment by JizKadasha** [comment]
The UI fixes were implemented.

**Comment by JizKadasha** [comment]
Error labels for lock screen forms were fixed.

**Comment by vantuz-subhuman** [comment]
Related to: https://github.com/Emurgo/yoroi-frontend/issues/148

**Comment by SebastienGllmt** [comment]
Replaced by #1968

**Pull request closed without merging**
