### PR TITLE
Denis/trezor emulator controller

### PR DESCRIPTION
**Pull request by Nebyt**
The cleaned version of the https://github.com/Emurgo/yoroi-frontend/pull/2908.
Added the trezor emulator controller to work with the trezor emulator run from the [trezor-user-env](https://github.com/trezor/trezor-user-env)

### CODE REVIEW

**Review by Nebyt — COMMENTED** [review]
/check

**Review by Nebyt — COMMENTED** [review]
/check

**Review by cmerloglb — APPROVED** [review]

**Review by Nebyt — COMMENTED** [review]
/check

**Review by Nebyt — COMMENTED** [review]
/check

**Pull request merged**
