### PR TITLE
Denis/yoext 372 smoke tests for mainnet

### PR DESCRIPTION
**Pull request by Nebyt**

### CODE REVIEW

**Review by zuzunker — COMMENTED** [review]
/check

**Review by Nebyt — COMMENTED** [review]
/check

**Review by zuzunker — COMMENTED** [review]
/check

**Review by zuzunker — COMMENTED** [review]
/check

**Review by zuzunker — COMMENTED** [review]
/release-check

**Review by zuzunker — COMMENTED** [review]
/release-check

**Review by zuzunker — COMMENTED** [review]
/release-check

**Review by Nebyt — COMMENTED** [review]
/release-check

**Review by zuzunker — COMMENTED** [review]
/release-check

**Pull request merged**
