### PR TITLE
fix(revamp): address all user-acceptance-testing revamp issues 

### PR DESCRIPTION
**Pull request by neuodev**
- [x] [UAT. Add wallets screen. Yoroi logo should be always clickable ](https://emurgo.atlassian.net/browse/YOEXT-821)
- [x] [UAT. Yoroi logo icon size is different from the design](https://emurgo.atlassian.net/browse/YOEXT-822)
- [x] [UAT. Opt-out analytics. Initial page. Difference from the design](https://emurgo.atlassian.net/browse/YOEXT-823)
- [x] [The first ToS page on the existing wallet is different from the design](https://emurgo.atlassian.net/browse/YOEXT-747)
- [x] [The "first-time user" screen. Difference from the design.](https://emurgo.atlassian.net/browse/YOEXT-749)
- [x] [Pages T&C and Privacy Policy are different from the design](https://emurgo.atlassian.net/browse/YOEXT-806)
- [x] [Opt-out analytics page is different from the design](https://emurgo.atlassian.net/browse/YOEXT-807)
- [x] [UAT. Nightly warning. Differencies from the design](https://emurgo.atlassian.net/browse/YOEXT-825)
- [x] [The Analytics page in Settings is different from the design](https://emurgo.atlassian.net/browse/YOEXT-808)
- [x] [UAT. Announcement modal has an outline](https://emurgo.atlassian.net/browse/YOEXT-826)
- [x] [UAT. Transactions page. Export modal. Difference from the design.](https://emurgo.atlassian.net/browse/YOEXT-829)
- [x] [UAT. Send page. Enter Address step. Difference from the design](https://emurgo.atlassian.net/browse/YOEXT-830)
- [x] [UAT. Send page. Step one. Excess error icon](https://emurgo.atlassian.net/browse/YOEXT-831)
- [x] [UAT. Receive page. Verify address modal. An incorrect position of the title](https://emurgo.atlassian.net/browse/YOEXT-832)
- [x] [UAT. Receive page. Generate URL modal. Difference from the design](https://emurgo.atlassian.net/browse/YOEXT-834)
- [x] [UAT. Receive page. Generated URL. Title position is incorrect](https://emurgo.atlassian.net/browse/YOEXT-835)

<details><summary>Language selection screen is revamped</summary>
<p>

Screenshot 2023-10-25 at 3 09 15 PM

Screenshot 2023-10-26 at 1 25 46 PM

</p>
</details>

<details><summary>Analytics screen is revamped</summary>
<p>

Screenshot 2023-10-26 at 2 15 11 PM

</p>
</details> 

<details><summary>First time user with ToS</summary>
<p>

Screenshot 2023-10-26 at 2 39 21 PM

</p>
</details>

### CODE REVIEW

**Comment by neuodev** [comment]
[autoscript] ⚠️ `fix/uat-revamp` doesn't full our branch naming convention.
Should follow `<tag>/<jira-ticket-id>/<short-name>`
<details>
<summary>Details</summary>

- `<tag>`: `fix`, `feat`, `chore`, `refactor`, `test`, ...
- `<jira-ticket-id>`: The issue ID of JIRA all capital letters
- `<short-name>`: A short and descriptive name for the branch
</details>

[](__JIRA_COMMENT_FLAG)

**Review by zuzunker — COMMENTED** [review]
/check

**Comment by neuodev** [comment]
@vsubhuman  it is not completed; I still have 15 other related tasks to complete.

**Review by zuzunker — COMMENTED** [review]
/check

**Review by zuzunker — APPROVED** [review]

**Pull request merged**
