### PR TITLE
E2E tests. Revive Firefox.

### PR DESCRIPTION
**Pull request by Nebyt**

### CODE REVIEW

**Comment by emurgo-rnd** [comment]
[YOEXT-1232: E2E tests. Revive Firefox.](https://emurgo.atlassian.net/browse/YOEXT-1232)

**Review by Nebyt — COMMENTED** [review]
/check

**Review by Nebyt — COMMENTED** [review]
/check

**Review by Nebyt — COMMENTED** [review]
/check

**Review by Nebyt — COMMENTED** [review]
/check

**Review by zuzunker — DISMISSED** [review]

**Review by zuzunker — APPROVED** [review]

**Pull request merged**
