### PR TITLE
Denis/yoext 594/trezor emu tests fix

### PR DESCRIPTION
**Pull request by Nebyt**

### CODE REVIEW

**Comment by neuodev** [comment]
[autoscirpt] Jira Ticket: **[Fix trezor emulator tests](https://emurgo.atlassian.net/browse/YOEXT-594)**

[](__JIRA_COMMENT_FLAG)

**Review by Nebyt — COMMENTED** [review]
/check

**Review by Nebyt — COMMENTED** [review]
/trezor-check

**Review by Nebyt — COMMENTED** [review]
/trezor-check

**Review by zuzunker — APPROVED** [review]

**Pull request merged**
