### PR TITLE
[create-wallet] Wallet loading screen

### PR DESCRIPTION
**Pull request by neuodev**
<details><summary>Details</summary>
<p>

https://user-images.githubusercontent.com/72753578/226985227-670a6c3f-7181-43c6-9a6b-c319e4240213.mov

</p>
</details>

### CODE REVIEW

**Comment by neuodev** [comment]
[autoscirpt] Jira Ticket: **[Add loading screen after create the new wallet](https://emurgo.atlassian.net/browse/YOEXT-549)**

[](__JIRA_COMMENT_FLAG)

**Review by nistadev — APPROVED** [review]

**Comment by neuodev** [comment]
@vsubhuman there are some broken changes because of the merge, need to fix it first!

**Comment by zuzunker** [comment]
> @vsubhuman there are some broken changes because of the merge, need to fix it first!

Thank you, @neuodev !

**Review by zuzunker — APPROVED** [review]

**Comment by neuodev** [comment]
@vsubhuman all fixed now!

**Review by zuzunker — APPROVED** [review]

**Pull request merged**
