### PR TITLE
Denis/disconnect test fixes

### PR DESCRIPTION
**Pull request by Nebyt**
Fixed "disconnect wallet" tests

### CODE REVIEW

**Review by Nebyt — COMMENTED** [review]
/check

**Review by Nebyt — COMMENTED** [review]
/check

**Review by Nebyt — COMMENTED** [review]
/check

**Review by Nebyt — COMMENTED** [review]
/check

**Review by Nebyt — COMMENTED** [review]
/check

**Review by zuzunker — APPROVED** [review]

**Review by Nebyt — COMMENTED** [review]
/check

**Review by Nebyt — COMMENTED** [review]
/check

**Pull request merged**
