### PR TITLE
Feature/enable themes

### PR DESCRIPTION
**Pull request by SebastienGllmt**
Now that we have the blog post written, we can enable this feature

image

**Please don't share** [the blog post](https://medium.com/@emurgo_io/custom-themes-in-yoroi-d3fa93f4b926) link until the feature is released 🙏

### CODE REVIEW

**Comment by SebastienGllmt** [comment]
Added some alignment code

image

**Comment by SebastienGllmt** [comment]
Added more spacing
image

**Comment by SebastienGllmt** [comment]
forgot to mention: Fix #314

**Comment by nicarq** [comment]
@SebastienGllmt I would hide the Yoroi Modern one because it’s incomplete :-/

**Pull request merged**
