### PR TITLE
Release / 4.20.0

### PR DESCRIPTION
**Pull request by zuzunker**
Milestone: https://github.com/Emurgo/yoroi-frontend/milestone/68?closed=1

## Change Set

- [x] https://github.com/Emurgo/yoroi-frontend/pull/3080 [@nistadev]
- [x] https://github.com/Emurgo/yoroi-frontend/pull/3125 [@neuodev]
- [x] https://github.com/Emurgo/yoroi-frontend/pull/3126 [@neuodev]
- [x] https://github.com/Emurgo/yoroi-frontend/pull/3130 [@neuodev]
- [x] https://github.com/Emurgo/yoroi-frontend/pull/3131 [@neuodev]
- [x] https://github.com/Emurgo/yoroi-frontend/pull/3134 [@neuodev]
- [x] https://github.com/Emurgo/yoroi-frontend/pull/3139 [@neuodev]
- [x] https://github.com/Emurgo/yoroi-frontend/pull/3142 [@neuodev]
- [x] https://github.com/Emurgo/yoroi-frontend/pull/3144 [@neuodev]
- [x] https://github.com/Emurgo/yoroi-frontend/pull/3152 [@neuodev]
- [x] https://github.com/Emurgo/yoroi-frontend/pull/3154 [@yushih]
- [x] https://github.com/Emurgo/yoroi-frontend/pull/3158 [@stackchain]
- [x] https://github.com/Emurgo/yoroi-frontend/pull/3168 [@neuodev]
- [x] https://github.com/Emurgo/yoroi-frontend/pull/3169
- [x] https://github.com/Emurgo/yoroi-frontend/pull/3172
- [x] https://github.com/Emurgo/yoroi-frontend/pull/3173 [@yushih]
- [x] https://github.com/Emurgo/yoroi-frontend/pull/3174 [@neuodev]
- [x] https://github.com/Emurgo/yoroi-frontend/pull/3175 [@nistadev]
- [x] https://github.com/Emurgo/yoroi-frontend/pull/3178 [@nistadev]
- [x] https://github.com/Emurgo/yoroi-frontend/pull/3179 [@vsubhuman]
- [x] https://github.com/Emurgo/yoroi-frontend/pull/3180 [@vsubhuman]
- [x] https://github.com/Emurgo/yoroi-frontend/pull/3181 [@nistadev]
- [x] https://github.com/Emurgo/yoroi-frontend/pull/3182 [@neuodev]
- [x] https://github.com/Emurgo/yoroi-frontend/pull/3183 [@neuodev]
- [x] https://github.com/Emurgo/yoroi-frontend/pull/3184 [@nistadev]
- [x] https://github.com/Emurgo/yoroi-frontend/pull/3186
- [x] https://github.com/Emurgo/yoroi-frontend/pull/3189 [@nistadev]
- [x] https://github.com/Emurgo/yoroi-frontend/pull/3190 [@nistadev]
- [x] https://github.com/Emurgo/yoroi-frontend/pull/3191 [@neuodev]
- [x] https://github.com/Emurgo/yoroi-frontend/pull/3192 [@neuodev]
- [x] https://github.com/Emurgo/yoroi-frontend/pull/3193 [@neuodev]
- [x] https://github.com/Emurgo/yoroi-frontend/pull/3194
- [x] https://github.com/Emurgo/yoroi-frontend/pull/3196 [@neuodev]

### CODE REVIEW

**Comment by neuodev** [comment]
[autoscript] ⚠️ `release/4.20.0` doesn't full our branch naming convention.
Should follow `<tag>/<jira-ticket-id>/<short-name>`
<details>
<summary>Details</summary>

- `<tag>`: `fix`, `feat`, `chore`, `refactor`, `test`, ...
- `<jira-ticket-id>`: The issue ID of JIRA all capital letters
- `<short-name>`: A short and descriptive name for the branch
</details>

[](__JIRA_COMMENT_FLAG)

**Comment by neuodev** [comment]
@vsubhuman Consider merging this PR https://github.com/Emurgo/yoroi-frontend/pull/3171. it is a nice addition.

**Comment by zuzunker** [comment]
> @vsubhuman Consider merging this PR #3171. it is a nice addition.

Thank you, @neuodev ! Will do

**Review by Nebyt — DISMISSED** [review]

**Comment by zuzunker** [comment]
Release: https://github.com/Emurgo/yoroi-frontend/releases/tag/4.20.6

**Pull request merged**
