### PR TITLE
Update sigma-rust to latest stable version

### PR DESCRIPTION
**Pull request by arobsn**
This PR updates sigma-rust to latest stable version and deals with some [breaking changes](https://github.com/ergoplatform/sigma-rust/releases/tag/v0.14.0) via the following changes:
  - updated `ergo-lib-wasm-browser` and `ergo-lib-wasm-nodejs` to `0.4.0` at `packages.json`
  - replaced all `to_bytes()` calls by `sigma_serialize_bytes()`

### CODE REVIEW

**Review by zuzunker — APPROVED** [review]

**Comment by zuzunker** [comment]
@anon-br , can you plz check the Flow and Lint? 🙏 Some of that fails in the checks

**Comment by arobsn** [comment]
Oh, sorry. Sore, will take a look ASAP.

**Comment by arobsn** [comment]
@vsubhuman flow types fixed!

**Review by zuzunker — COMMENTED** [review]
/check

**Review by zuzunker — APPROVED** [review]

**Pull request merged**
