### PR TITLE
update dependencies to fix npm audit alerts (non critical)

### PR DESCRIPTION
**Pull request by nicarq**
update dependencies to fix npm audit issues. it’s important to notice that from the critical and moderate vulnerabilities are an issue if Yoroi were a server - which is not -.

```
found 75 vulnerabilities (64 low, 4 moderate, 7 high) in 27288 scanned packages
  run `npm audit fix` to fix 4 of them.
  68 vulnerabilities require semver-major dependency updates.
  3 vulnerabilities require manual review. See the full report for details.
```

to

```
added 1644 packages from 1152 contributors and audited 867368 packages in 26.977s
found 0 vulnerabilities
```

### CODE REVIEW

**Comment by nicarq** [comment]
[ch808]

**Comment by SebastienGllmt** [comment]
I noticed this moves packages from strict-version to loose-version. Is this intended?

**Comment by nicarq** [comment]
@SebastienGllmt yeah, they should be fixed. I updated them and also other dependencies that were not fixed.

**Comment by SebastienGllmt** [comment]
Looks like something is going wrong with this on Chrome (restarting CI doesn't fix it)

**Pull request merged**
